setwd("/media/charleshugo/SilverToshiba/事务数据/个人事务/学习/DataScience/edX_The_Analytics_Edge/")
wine = read.csv("wine.csv")
str(wine)
summary(wine)
model1 = lm (Price ~ AGST, data = wine)
summary(model1)
model2 = lm (Price ~ AGST, data = wine)
sum(model1$residuals^2)
model2 = lm (Price ~ AGST + HarvestRain, data = wine)
summary(model2)
sum(model2$residuals^2)
model3 = lm (Price ~ AGST + HarvestRain + WinterRain + Age + FrancePop, data = wine)
summary(model3)
sum(model3$residuals^2)
model4 = lm (Price ~ AGST + HarvestRain + WinterRain + Age + FrancePop + Year, data = wine)
summary(model4)
sum(model4$residuals^2)
model5 = lm (Price ~ HarvestRain + WinterRain , data = wine)
summary(model5)
sum(model5$residuals^2)
